name: Run Python

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      API_KEY_TEST1: ${{ secrets.API_KEY_TEST1 }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run script
        run: python main/test_env1.py
